version: '3'
services:
  auth-svc:
    image: online-shop-auth-svc
    build: .
    command: go run cmd/main.go
    ports:
      - 50051:50051

  postgreSQL:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=auth_svc
      - POSTGRES_PASSWORD=aklpidor
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
