version: '3'
services:
  postgreSQL:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=auth_svc
      - POSTGRES_PASSWORD=aklpidor
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
